# Setup
title: Ofir Sharony - Mostly Makes Sense
description: A blog about engineering leadership, personal stories, and things I'm proud of.
url: https://ofirsharony.github.io/
paginate: 1
baseurl: ""
permalink: pretty
incremental: false

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-98JC157PYZ

# Specify the author for blog posts
author:
  name: Ofir Sharony
  url: https://linktr.ee/ofirsharony
  email: ofirsharony@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
